# Jekyll configuration file for site settings and options
# such as the Markdown processor.

title: GitHub Pages Test Page
description: A page for testing the rendering of a GitHub Page.
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
